# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to=b'')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.Carrera')),
            ],
        ),
    ]
