# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='name',
        ),
    ]
